sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t stevehanphoto/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stevehanphoto/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-164673570568"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
